-- Synthetic data only. Independent schemas deliberately avoid cross-schema dependencies.
CREATE SCHEMA sales;
CREATE SCHEMA hr;
CREATE SCHEMA internal;

CREATE TABLE sales.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text NOT NULL,
    amount integer NOT NULL
);
CREATE TABLE sales.events (id bigint PRIMARY KEY, description text NOT NULL);
CREATE TABLE hr.people (id bigint PRIMARY KEY, description text NOT NULL);
CREATE TABLE internal.audit (id bigint PRIMARY KEY, description text NOT NULL);

INSERT INTO sales.orders (description, amount)
SELECT 'initial-' || n, n * 10 FROM generate_series(1, 100) n;
INSERT INTO sales.events VALUES (1, 'initial-event');
INSERT INTO hr.people VALUES (1, 'initial-person');
INSERT INTO internal.audit VALUES (1, 'must-not-replicate');